// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf-A6d-coSgNHXPDo32NZdty_aRItwkQo',
    appId: '1:936214269434:web:a1d0ab5d2465c32f82e843',
    messagingSenderId: '936214269434',
    projectId: 'masterclass-6b8b9',
    authDomain: 'masterclass-6b8b9.firebaseapp.com',
    storageBucket: 'masterclass-6b8b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn1e379OJZD4k_w1I67N8IyzpURYiyaZ8',
    appId: '1:936214269434:android:bda8de0fb365564482e843',
    messagingSenderId: '936214269434',
    projectId: 'masterclass-6b8b9',
    storageBucket: 'masterclass-6b8b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN_50MeYsnDXLU7mlXpGyCkWUKSqTIQEw',
    appId: '1:936214269434:ios:6caf56c12bb9702282e843',
    messagingSenderId: '936214269434',
    projectId: 'masterclass-6b8b9',
    storageBucket: 'masterclass-6b8b9.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN_50MeYsnDXLU7mlXpGyCkWUKSqTIQEw',
    appId: '1:936214269434:ios:3dd5e5b66f612bf482e843',
    messagingSenderId: '936214269434',
    projectId: 'masterclass-6b8b9',
    storageBucket: 'masterclass-6b8b9.appspot.com',
    iosBundleId: 'com.example.app1.RunnerTests',
  );
}
